CREATE DATABASE SALES;
USE SALES;
SHOW TABLES;

SELECT*FROM SALES_CSV LIMIT 10;

SELECT 	
	EXTRACT(YEAR FROM `Order Date`) AS YEAR,
    EXTRACT(MONTH FROM `Order Date`) AS MONTH,
    SUM(SALES) AS TOTAL_REVENUE,	
    COUNT(DISTINCT `Order ID`) AS ORDER_VOLUME	
FROM SALES_CSV	
WHERE `Order Date` BETWEEN '2014-01-01' AND '2017-12-31'
GROUP BY 
	    EXTRACT(YEAR FROM `Order Date`),
        EXTRACT(MONTH FROM `Order Date`)
ORDER BY 
      YEAR,
      MONTH;	
